// import { GiftCard } from '../types';

// export const mockGiftCards: GiftCard[] = [
//   {
//     id: 'gc_fdc_samsclub',
//     merchant: 'Fogo de Chão',
//     discountPercent: 20,
//     availableAmount: 100,
//     price: 80,
//     source: 'Sam\'s Club',
//     category: 'Restaurant',
//   },
//   {
//     id: 'gc_sw_samsclub1',
//     merchant: 'Southwest Airlines',
//     discountPercent: 5,
//     availableAmount: 500,
//     price: 475,
//     source: 'Sam\'s Club',
//     category: 'Travel',
//   },
//   {
//     id: 'gc_sw_samsclub2',
//     merchant: 'Southwest Airlines',
//     discountPercent: 5,
//     availableAmount: 250,
//     price: 237.5,
//     source: 'Sam\'s Club',
//     category: 'Travel',
//   },
//   {
//     id: 'gc_saltgrass_samsclub',
//     merchant: 'Saltgrass Steakhouse',
//     discountPercent: 20,
//     availableAmount: 100,
//     price: 80,
//     source: 'Sam\'s Club',
//     category: 'Restaurant',
//   },
//   {
//     id: 'gc_bubbagump_samsclub',
//     merchant: 'Bubba Gump Shrimp Co.',
//     discountPercent: 20,
//     availableAmount: 100,
//     price: 80,
//     source: 'Sam\'s Club',
//     category: 'Restaurant',
//   },
//   {
//     id: 'gc_xbox_samsclub',
//     merchant: 'Xbox',
//     discountPercent: 10,
//     availableAmount: 100,
//     price: 90,
//     source: 'Sam\'s Club',
//     category: 'Entertainment',
//   },
//   {
//     id: 'gc_wendys_samsclub',
//     merchant: 'Wendys',
//     discountPercent: 20,
//     availableAmount: 60,
//     price: 48,
//     source: 'Sam\'s Club',
//     category: 'Restaurant',
//   },
//   {
//     id: 'gc_coldstone_samsclub',
//     merchant: 'Coldstone Creamery',
//     discountPercent: 33,
//     availableAmount: 30,
//     price: 20,
//     source: 'Sam\'s Club',
//     category: 'Restaurant',
//   },
//   {
//     id: 'gc_topgolf_samsclub',
//     merchant: 'Top Golf',
//     discountPercent: 20,
//     availableAmount: 75,
//     price: 60,
//     source: 'Sam\'s Club',
//     category: 'Entertainment',
//   },
//   {
//     id: 'gc_cinemark_samsclub',
//     merchant: 'Cinemark',
//     discountPercent: 20,
//     availableAmount: 50,
//     price: 40,
//     source: 'Sam\'s Club',
//     category: 'Entertainment',
//   },
//   {
//     id: 'gc_petsmart_samsclub',
//     merchant: 'PetSmart',
//     discountPercent: 10,
//     availableAmount: 100,
//     price: 90,
//     source: 'Sam\'s Club',
//     category: 'Grocery',
//   },{
//     id: 'gc_redlobster_samsclub',
//     merchant: 'Red Lobster',
//     discountPercent: 20,
//     availableAmount: 100,
//     price: 80,
//     source: 'Sam\'s Club',
//     category: 'Restaurant',
//   },
//   {
//     id: 'gc_potbelly_samsclub',
//     merchant: 'Potbelly',
//     discountPercent: 25,
//     availableAmount: 50,
//     price: 40,
//     source: 'Sam\'s Club',
//     category: 'Restaurant',
//   },
//   {
//     id: 'gc_pfchangs_samsclub',
//     merchant: 'P.F. Chang\'s',
//     discountPercent: 20,
//     availableAmount: 50,
//     price: 40,
//     source: 'Sam\'s Club',
//     category: 'Restaurant',
//   },
//   {
//     id: 'gc_quince_samsclub',
//     merchant: 'Quince',
//     discountPercent: 20,
//     availableAmount: 50,
//     price: 40,
//     source: 'Sam\'s Club',
//     category: 'Retail',
//   },
//   {
//     id: 'gc_amc_samsclub',
//     merchant: 'KFC',
//     discountPercent: 20,
//     availableAmount: 50,
//     price: 40,
//     source: 'Sam\'s Club',
//     category: 'Restaurant',
//   },
//   {
//     id: 'gc_uber_costco',
//     merchant: 'Uber',
//     discountPercent: 20,
//     availableAmount: 100,
//     price: 80,
//     source: 'Costco',
//     category: 'Travel',
//   },
// ];

// export const getGiftCardByMerchant = (merchantName: string): GiftCard | undefined => {
//   return mockGiftCards.find(
//     (gc) => gc.merchant.toLowerCase() === merchantName.toLowerCase()
//   );
// };

// export const getAllGiftCards = (): GiftCard[] => {
//   return mockGiftCards;
// };
